import 'dart:developer';

import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_timezone/flutter_timezone.dart';
import 'package:timezone/data/latest.dart' as tz;
import 'package:timezone/timezone.dart' as tz;

import '../domain/smart_notification.dart';

/// Platform adapter for delivering and scheduling local Imaanly notifications.
class LocalNotificationService {
  LocalNotificationService._();

  static final LocalNotificationService instance = LocalNotificationService._();

  final FlutterLocalNotificationsPlugin _plugin =
      FlutterLocalNotificationsPlugin();

  bool _initialized = false;
  bool _timezoneInitialized = false;

  static const _channelId = 'imaanly_smart_notifications';
  static const _channelName = 'Imaanly reminders';
  static const _channelDescription =
      'Personal worship reminders generated by Imaanly.';

  Future<void> initialize() async {
    if (_initialized) return;

    const android = AndroidInitializationSettings('@mipmap/ic_launcher');
    const darwin = DarwinInitializationSettings(
      requestAlertPermission: false,
      requestBadgePermission: false,
      requestSoundPermission: false,
    );
    const linux = LinuxInitializationSettings(
      defaultActionName: 'Open Imaanly',
    );

    await _plugin.initialize(
      const InitializationSettings(
        android: android,
        iOS: darwin,
        macOS: darwin,
        linux: linux,
      ),
    );

    await _plugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(const AndroidNotificationChannel(
          _channelId,
          _channelName,
          description: _channelDescription,
          importance: Importance.high,
        ));

    await _initializeDeviceTimezone();
    _initialized = true;
  }

  Future<bool> requestPermissions() async {
    await initialize();

    final androidGranted = await _plugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.requestNotificationsPermission();

    final iosGranted = await _plugin
        .resolvePlatformSpecificImplementation<
            IOSFlutterLocalNotificationsPlugin>()
        ?.requestPermissions(alert: true, badge: true, sound: true);

    final macGranted = await _plugin
        .resolvePlatformSpecificImplementation<
            MacOSFlutterLocalNotificationsPlugin>()
        ?.requestPermissions(alert: true, badge: true, sound: true);

    return androidGranted ?? iosGranted ?? macGranted ?? true;
  }

  Future<void> deliver(SmartNotificationCandidate candidate) async {
    await initialize();
    await _plugin.show(
      _notificationId(candidate),
      candidate.title,
      candidate.body,
      _details(),
      payload: candidate.reason,
    );
  }

  /// Schedules a prayer reminder at the requested device-local date/time.
  ///
  /// Past occurrences are ignored. A stable ID makes rescheduling the same
  /// prayer/date replace the previous occurrence instead of duplicating it.
  Future<void> schedulePrayerReminder({
    required String prayerName,
    required DateTime prayerAt,
    int reminderMinutes = 10,
    bool silent = false,
  }) async {
    await initialize();

    final scheduledAt = prayerAt.subtract(Duration(minutes: reminderMinutes));
    if (!scheduledAt.isAfter(DateTime.now())) return;

    final details = NotificationDetails(
      android: AndroidNotificationDetails(
        _channelId,
        _channelName,
        channelDescription: _channelDescription,
        importance: silent ? Importance.low : Importance.high,
        priority: silent ? Priority.low : Priority.high,
        playSound: !silent,
        category: AndroidNotificationCategory.alarm,
      ),
      iOS: DarwinNotificationDetails(presentSound: !silent),
      macOS: DarwinNotificationDetails(presentSound: !silent),
      linux: const LinuxNotificationDetails(
        urgency: LinuxNotificationUrgency.normal,
      ),
    );

    final id = _prayerNotificationId(prayerName, prayerAt);
    await _plugin.zonedSchedule(
      id,
      '$prayerName is approaching',
      reminderMinutes <= 0
          ? 'It is time for $prayerName.'
          : '$prayerName begins in $reminderMinutes minutes.',
      tz.TZDateTime.from(scheduledAt, tz.local),
      details,
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      payload: 'prayer:${prayerName.toLowerCase()}',
    );
  }

  Future<void> cancelPrayerReminder({
    required String prayerName,
    required DateTime prayerAt,
  }) async {
    await initialize();
    await _plugin.cancel(_prayerNotificationId(prayerName, prayerAt));
  }

  Future<void> cancelAll() async {
    await initialize();
    await _plugin.cancelAll();
  }

  Future<void> _initializeDeviceTimezone() async {
    if (_timezoneInitialized) return;

    tz.initializeTimeZones();
    _timezoneInitialized = true;

    try {
      final timezoneName = await FlutterTimezone.getLocalTimezone();
      tz.setLocalLocation(tz.getLocation(timezoneName));
    } catch (error, stackTrace) {
      // The bundled timezone database remains a safe fallback when a platform
      // cannot expose its IANA timezone identifier.
      log(
        'Could not resolve device timezone; using timezone package default: $error',
        name: 'LocalNotificationService',
        stackTrace: stackTrace,
      );
    }
  }

  NotificationDetails _details() => const NotificationDetails(
        android: AndroidNotificationDetails(
          _channelId,
          _channelName,
          channelDescription: _channelDescription,
          importance: Importance.high,
          priority: Priority.high,
          category: AndroidNotificationCategory.reminder,
        ),
        iOS: DarwinNotificationDetails(),
        macOS: DarwinNotificationDetails(),
        linux: LinuxNotificationDetails(
          urgency: LinuxNotificationUrgency.normal,
        ),
      );

  int _notificationId(SmartNotificationCandidate candidate) {
    final key = '${candidate.category.name}:${candidate.reason}:${candidate.title}';
    return _stableHash(key);
  }

  int _prayerNotificationId(String prayerName, DateTime prayerAt) {
    final day = '${prayerAt.year}-${prayerAt.month}-${prayerAt.day}';
    return _stableHash('prayer:$day:${prayerName.toLowerCase()}');
  }

  int _stableHash(String value) {
    var hash = 0;
    for (final unit in value.codeUnits) {
      hash = 0x1fffffff & (hash + unit);
      hash = 0x1fffffff & (hash + ((hash & 0x0007ffff) << 10));
      hash ^= hash >> 6;
    }
    return hash & 0x7fffffff;
  }

  void logError(Object error, StackTrace stackTrace) {
    log('Local notification error: $error',
        name: 'LocalNotificationService', stackTrace: stackTrace);
  }
}
