import 'dart:developer';

import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import '../domain/smart_notification.dart';

/// Platform adapter for delivering the app's locally generated notifications.
///
/// Policy decisions remain in [SmartNotificationCoordinator]; this service only
/// owns plugin initialization, permissions and delivery.
class LocalNotificationService {
  LocalNotificationService._();

  static final LocalNotificationService instance = LocalNotificationService._();

  final FlutterLocalNotificationsPlugin _plugin =
      FlutterLocalNotificationsPlugin();

  bool _initialized = false;

  static const _channelId = 'imaanly_smart_notifications';
  static const _channelName = 'Imaanly reminders';
  static const _channelDescription =
      'Personal worship reminders generated by Imaanly.';

  Future<void> initialize() async {
    if (_initialized) return;

    const android = AndroidInitializationSettings('@mipmap/ic_launcher');
    const darwin = DarwinInitializationSettings(
      requestAlertPermission: false,
      requestBadgePermission: false,
      requestSoundPermission: false,
    );
    const linux = LinuxInitializationSettings(
      defaultActionName: 'Open Imaanly',
    );

    await _plugin.initialize(
      const InitializationSettings(
        android: android,
        iOS: darwin,
        macOS: darwin,
        linux: linux,
      ),
    );

    await _plugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(const AndroidNotificationChannel(
          _channelId,
          _channelName,
          description: _channelDescription,
          importance: Importance.high,
        ));

    _initialized = true;
  }

  Future<bool> requestPermissions() async {
    await initialize();

    final androidGranted = await _plugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.requestNotificationsPermission();

    final iosGranted = await _plugin
        .resolvePlatformSpecificImplementation<
            IOSFlutterLocalNotificationsPlugin>()
        ?.requestPermissions(alert: true, badge: true, sound: true);

    final macGranted = await _plugin
        .resolvePlatformSpecificImplementation<
            MacOSFlutterLocalNotificationsPlugin>()
        ?.requestPermissions(alert: true, badge: true, sound: true);

    return androidGranted ?? iosGranted ?? macGranted ?? true;
  }

  Future<void> deliver(SmartNotificationCandidate candidate) async {
    await initialize();

    final id = _notificationId(candidate);
    await _plugin.show(
      id,
      candidate.title,
      candidate.body,
      const NotificationDetails(
        android: AndroidNotificationDetails(
          _channelId,
          _channelName,
          channelDescription: _channelDescription,
          importance: Importance.high,
          priority: Priority.high,
          category: AndroidNotificationCategory.reminder,
        ),
        iOS: DarwinNotificationDetails(),
        macOS: DarwinNotificationDetails(),
        linux: LinuxNotificationDetails(
          urgency: LinuxNotificationUrgency.normal,
        ),
      ),
      payload: candidate.reason,
    );
  }

  Future<void> cancelAll() => _plugin.cancelAll();

  int _notificationId(SmartNotificationCandidate candidate) {
    final key = '${candidate.category.name}:${candidate.reason}:${candidate.title}';
    var hash = 0;
    for (final unit in key.codeUnits) {
      hash = 0x1fffffff & (hash + unit);
      hash = 0x1fffffff & (hash + ((hash & 0x0007ffff) << 10));
      hash ^= hash >> 6;
    }
    return hash & 0x7fffffff;
  }

  void logError(Object error, StackTrace stackTrace) {
    log('Local notification error: $error',
        name: 'LocalNotificationService', stackTrace: stackTrace);
  }
}
