org.gradle.jvmargs=-Xmx6144m -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
android.enableJetifier=true
android.useAndroidX=true
android.r8.optimizedResourceShrinking=true
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
kotlin.compiler.execution.strategy=out-of-process
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
