/// English titles for the Hisn al-Muslim adhkar chapters.
/// The Arabic chapter name (as stored in the data) is the key.
const Map<String, String> azkarCategoryNames = {
  "أذكار الصباح": "Morning Adhkar",
  "أذكار المساء": "Evening Adhkar",
  "أذكار الاستيقاظ من النوم": "Adhkar upon Waking Up",
  "دعاء لبس الثوب": "Supplication when Dressing",
  "دعاء لبس الثوب الجديد": "Supplication when Wearing New Clothes",
  "الدعاء لمن لبس ثوبا جديدا": "Supplication for Someone Wearing New Clothes",
  "ما يقول إذا وضع الثوب": "What to Say when Taking Off Clothes",
  "دعاء دخول الخلاء - الحمام": "Supplication when Entering the Toilet",
  "دعاء الخروج من الخلاء - الحمام": "Supplication when Leaving the Toilet",
  "الذكر قبل الوضوء": "Remembrance before Wudu",
  "الذكر بعد الفراغ من الوضوء": "Remembrance after Completing Wudu",
  "الذكر عند الخروج من المنزل": "Remembrance when Leaving the Home",
  "الذكر عند دخول المنزل": "Remembrance when Entering the Home",
  "دعاء الذهاب إلى المسجد": "Supplication when Going to the Mosque",
  "دعاء دخول المسجد": "Supplication when Entering the Mosque",
  "دعاء الخروج من المسجد": "Supplication when Leaving the Mosque",
  "أذكار الأذان": "Adhkar of the Adhan",
  "دعاء الاستفتاح": "Opening Supplication of the Prayer",
  "دعاء الركوع": "Supplication in Ruku (Bowing)",
  "دعاء الرفع من الركوع": "Supplication when Rising from Ruku",
  "دعاء السجود": "Supplication in Sujud (Prostration)",
  "دعاء الجلسة بين السجدتين": "Supplication between the Two Prostrations",
  "دعاء سجود التلاوة": "Supplication for the Prostration of Recitation",
  "التشهد": "The Tashahhud",
  "الصلاة على النبي بعد التشهد": "Sending Blessings on the Prophet after the Tashahhud",
  "الدعاء بعد التشهد الأخير قبل السلام": "Supplication after the Final Tashahhud before the Salam",
  "الأذكار بعد السلام من الصلاة": "Adhkar after the Salam of the Prayer",
  "دعاء صلاة الاستخارة": "Supplication of the Istikhara Prayer",
  "أذكار النوم": "Adhkar before Sleep",
  "الدعاء إذا تقلب في الليل": "Supplication when Turning Over in the Night",
  "دعاء الفزع في النوم و من بلي بالوحشة": "Supplication for Fear or Unease during Sleep",
  "ما يفعل من رأى الرؤيا أو الحلم في النوم": "What to Do after a Dream or Nightmare",
  "دعاء قنوت الوتر": "Qunut Supplication in Witr",
  "الذكر عقب السلام من الوتر": "Remembrance after the Salam of Witr",
  "دعاء الهم والحزن": "Supplication for Worry and Grief",
  "دعاء الكرب": "Supplication for Distress",
  "دعاء لقاء العدو و ذي السلطان": "Supplication when Meeting the Enemy or a Ruler",
  "دعاء من خاف ظلم السلطان": "Supplication for One Who Fears the Oppression of a Ruler",
  "الدعاء على العدو": "Supplication against the Enemy",
  "ما يقول من خاف قوما": "What to Say when Fearing a People",
  "دعاء من أصابه وسوسة في الإيمان": "Supplication for One Struck by Doubts in Faith",
  "دعاء قضاء الدين": "Supplication for Settling a Debt",
  "دعاء الوسوسة في الصلاة و القراءة": "Supplication for Whispers in Prayer and Recitation",
  "دعاء من استصعب عليه أمر": "Supplication when a Matter is Difficult",
  "ما يقول ويفعل من أذنب ذنباً": "What to Say and Do after Committing a Sin",
  "دعاء طرد الشيطان و وساوسه": "Supplication for Repelling Satan and His Whispers",
  "الدعاء حينما يقع ما لا يرضاه أو غلب على أمره": "Supplication when Something Unwanted Happens or One is Overwhelmed",
  "ﺗﻬنئة المولود له وجوابه": "Congratulating the Parent of a Newborn and the Reply",
  "ما يعوذ به الأولاد - رقية": "Seeking Refuge for Children (Ruqyah)",
  "الدعاء للمريض في عيادته": "Supplication for the Sick when Visiting Them",
  "فضل عيادة المريض": "The Virtue of Visiting the Sick",
  "دعاء المريض الذي يئس من حياته": "Supplication of the Sick Who Has Lost Hope of Recovery",
  "تلقين المحتضر": "Prompting the Dying Person (Talqin)",
  "دعاء من أصيب بمصيبة": "Supplication for One Struck by Calamity",
  "الدعاء عند إغماض الميت": "Supplication when Closing the Eyes of the Deceased",
  "الدعاء للميت في الصلاة عليه": "Supplication for the Deceased in the Funeral Prayer",
  "الدعاء للفرط في الصلاة عليه": "Supplication for a Deceased Child in the Funeral Prayer",
  "دعاء التعزية": "Supplication of Condolence",
  "الدعاء عند إدخال الميت القبر": "Supplication when Placing the Deceased in the Grave",
  "الدعاء بعد دفن الميت": "Supplication after Burying the Deceased",
  "دعاء زيارة القبور": "Supplication for Visiting Graves",
  "دعاء الريح": "Supplication when the Wind Blows",
  "دعاء الرعد": "Supplication when Hearing Thunder",
  "من أدعية الاستسقاء": "Supplications for Rain (Istisqa)",
  "الدعاء إذا نزل المطر": "Supplication when Rain Falls",
  "الذكر بعد نزول المطر": "Remembrance after the Rain",
  "من أدعية الاستصحاء": "Supplication for Clear Skies",
  "دعاء رؤية الهلال": "Supplication on Sighting the New Moon",
  "الدعاء عند إفطار الصائم": "Supplication when Breaking the Fast",
  "الدعاء قبل الطعام": "Supplication before Eating",
  "الدعاء عند الفراغ من الطعام": "Supplication after Finishing Eating",
  "دعاء الضيف لصاحب الطعام": "Guest's Supplication for the Host",
  "التعريض بالدعاء لطلب الطعام أو الشراب": "Hinting at a Supplication to Ask for Food or Drink",
  "الدعاء إذا أفطر عند أهل بيت": "Supplication when Breaking Fast at Someone's Home",
  "دعاء الصائم إذا حضر الطعام ولم يفطر": "Fasting Person's Response when Food is Offered",
  "ما يقول الصائم إذا سابه أحد": "What a Fasting Person Says when Insulted",
  "الدعاء عند رؤية باكورة الثمر": "Supplication on Seeing the First Fruits",
  "دعاء العطاس": "Supplication for Sneezing",
  "ما يقال للكافر إذا عطس فحمد الله": "What to Say to a Disbeliever Who Sneezes and Praises Allah",
  "الدعاء للمتزوج": "Supplication for the Newly Married",
  "دعاء المتزوج و شراء الدابة": "Supplication of the Newly Married and when Buying an Animal",
  "الدعاء قبل إتيان الزوجة - الجماع": "Supplication before Intimacy with One's Spouse",
  "دعاء الغضب": "Supplication for Anger",
  "دعاء من رأى مبتلى": "Supplication on Seeing Someone Afflicted",
  "ما يقال في اﻟﻤﺠلس": "What is Said in a Gathering",
  "كفارة اﻟﻤﺠلس": "Expiation of a Gathering",
  "الدعاء لمن قال غفر الله لك": "Reply to Someone Who Says \"May Allah Forgive You\"",
  "الدعاء لمن صنع إليك معروفا": "Supplication for Someone Who Has Done You a Favor",
  "ما يعصم الله به من الدجال": "What Protects from the Dajjal",
  "الدعاء لمن قال إني أحبك في الله": "Reply to Someone Who Says \"I Love You for the Sake of Allah\"",
  "الدعاء لمن عرض عليك ماله": "Supplication for One Who Offers You Their Wealth",
  "الدعاء لمن أقرض عند القضاء": "Supplication for One Who Lent You when Repaying",
  "دعاء الخوف من الشرك": "Supplication for Fear of Shirk",
  "الدعاء لمن قال بارك الله فيك": "Reply to Someone Who Says \"May Allah Bless You\"",
  "دعاء كراهية الطيرة": "Supplication for Disliking Bad Omens",
  "دعاء الركوب": "Supplication when Riding",
  "دعاء السفر": "Travel Supplication",
  "دعاء دخول القرية أو البلدة": "Supplication when Entering a Town or City",
  "دعاء دخول السوق": "Supplication when Entering the Market",
  "الدعاء إذا تعس المركوب": "Supplication when One's Mount Stumbles",
  "دعاء المسافر للمقيم": "Traveler's Supplication for the One Staying Behind",
  "دعاء المقيم للمسافر": "Resident's Supplication for the Traveler",
  "التكبير و التسبيح في سير السفر": "Takbir and Tasbih while Traveling",
  "دعاء المسافر إذا أسحر": "Traveler's Supplication at Dawn",
  "الدعاء إذا نزل متزلا في سفر أو غيره": "Supplication when Stopping at a Place on a Journey",
  "ذكر الرجوع من السفر": "Remembrance upon Returning from Travel",
  "ما يقول من أتاه أمر يسره أو يكرهه": "What to Say upon Receiving Pleasing or Displeasing News",
  "فضل الصلاة على النبي صلى الله عليه و سلم": "The Virtue of Sending Blessings on the Prophet ﷺ",
  "إفشاء السلام": "Spreading the Greeting of Peace",
  "كيف يرد السلام على الكافر إذا سلم": "How to Reply to a Non-Muslim's Greeting",
  "الدعاء عند سماع صياح الديك ونهيق الحمار": "Supplication when Hearing a Rooster Crow or a Donkey Bray",
  "الدعاء عند سماع نباح الكلاب بالليل": "Supplication when Hearing Dogs Bark at Night",
  "الدعاء لمن سببته": "Supplication for Someone You Have Insulted",
  "ما يقول المسلم إذا مدح المسلم": "What a Muslim Says when Praised by Another Muslim",
  "ما يقول المسلم إذا زكي": "What a Muslim Says when Commended",
  "كيف يلبي المحرم في الحج أو العمرة ؟": "How the Pilgrim Recites the Talbiyah in Hajj or Umrah",
  "التكبير إذا أتى الركن الأسود": "Takbir upon Reaching the Black Stone",
  "الدعاء بين الركن اليماني والحجر الأسود": "Supplication between the Yemeni Corner and the Black Stone",
  "دعاء الوقوف على الصفا والمروة": "Supplication while Standing on Safa and Marwa",
  "الدعاء يوم عرفة": "Supplication on the Day of Arafah",
  "الذكر عند المشعر الحرام": "Remembrance at al-Mash'ar al-Haram",
  "التكبير عند رمي الجمار مع كل حصاة": "Takbir when Throwing Each Pebble",
  "دعاء التعجب والأمر السار": "Supplication for Amazement and Pleasant News",
  "ما يفعل من أتاه أمر يسره": "What to Do upon Receiving Pleasing News",
  "ما يقول من أحس وجعا في جسده": "What to Say when Feeling Pain in the Body",
  "دعاء من خشي أن يصيب شيئا بعينه": "Supplication for One Who Fears Harming Something with the Evil Eye",
  "ما يقال عند الفزع": "What is Said when Frightened",
  "ما يقول عند الذبح أو النحر": "What to Say when Slaughtering or Sacrificing",
  "ما يقول لرد كيد مردة الشياطين": "What to Say to Repel the Plots of Rebellious Devils",
  "الاستغفار و التوبة": "Seeking Forgiveness and Repentance",
  "فضل التسبيح والتحميد، والتهليل، والتكبير": "The Virtue of Tasbih, Tahmid, Tahlil and Takbir",
  "كيف كان النبي ﷺ يسبح؟": "How the Prophet ﷺ Used to Glorify Allah",
  "من أنواع الخير والآداب الجامعة": "Various Good Deeds and Comprehensive Etiquette",
};

/// Returns the English title for an adhkar chapter, or the original name if unknown.
String azkarCategoryTitle(String arabicName) => azkarCategoryNames[arabicName.trim()] ?? arabicName;

/// "1 dhikr" / "24 adhkar".
String adhkarCountLabel(int count) => count == 1 ? '1 dhikr' : '$count adhkar';
