import "package:imaanly/src/core/bootstrap/app_bootstrap_coordinator.dart";
import "package:imaanly/src/core/di/service_locator.dart";
import "package:imaanly/src/core/reader_session/reader_session_repository.dart";
import "package:imaanly/src/core/settings/settings_repository.dart";
import "package:imaanly/src/core/storage/app_boxes.dart";
import "package:imaanly/src/core/unified_quran_settings/cubit/quran_settings_cubit.dart";
import "package:imaanly/src/core/error/release_error_handler.dart";
import "package:imaanly/src/core/services/ayah_of_the_day_service.dart";
import "package:imaanly/src/platform_services.dart" as platform_services;
import "package:imaanly/src/resources/translation/language_cubit.dart";
import "package:imaanly/src/resources/translation/languages.dart";
import "package:imaanly/src/screen/location_handler/model/location_data_qibla_data_state.dart";
import "package:imaanly/src/screen/prayer_time/cubit/prayer_time_cubit.dart";
import "package:imaanly/src/screen/quran_reader/cubit/reader_ui_cubit.dart";
import "package:imaanly/src/screen/quran_script_view/cubit/ayah_by_ayah_in_scroll_info_cubit.dart";
import "package:imaanly/src/screen/quran_script_view/cubit/ayah_to_highlight.dart";
import "package:imaanly/src/screen/quran_script_view/cubit/landscape_scroll_effect.dart";
import "package:imaanly/src/screen/settings/cubit/quran_script_view_cubit.dart";
import "package:imaanly/src/screen/setup/cubit/resources_progress_cubit_cubit.dart";
import "package:imaanly/core/auth/auth_cubit.dart";
import "package:imaanly/src/theme/app_theme.dart";
import "package:imaanly/src/theme/controller/theme_cubit.dart";
import "package:imaanly/src/theme/controller/theme_state.dart";
import "package:imaanly/src/core/audio/services/idrisium_audio_tracker.dart";
import "package:imaanly/src/widget/history/cubit/quran_history_cubit.dart";
import "package:imaanly/src/widget/quran_script_words/cubit/word_playing_state_cubit.dart";
import "package:imaanly/src/features/islamic_knowledge/presentation/islamic_knowledge_screen.dart";
import "package:flutter/cupertino.dart";
import "package:flutter/material.dart";
import "package:flutter/services.dart";
import "package:flutter_bloc/flutter_bloc.dart";
import "package:flutter_localizations/flutter_localizations.dart";
import "package:flutter_native_splash/flutter_native_splash.dart";
import "package:flutter_screenutil/flutter_screenutil.dart";
import "package:google_fonts/google_fonts.dart";
import "package:hive_ce_flutter/hive_flutter.dart";
import "package:just_audio_background/just_audio_background.dart";
import "package:just_audio_media_kit/just_audio_media_kit.dart";
import "package:shared_preferences/shared_preferences.dart";
import "package:imaanly/core/services/firebase_service.dart";
import "package:imaanly/features/analytics/services/analytics_tracker.dart";
import "package:imaanly/features/home/presentation/imaanly_home_page.dart";

String? applicationDataPath;
platform_services.PlatformOwn platformOwn = platform_services.getPlatform();

Future<void> _safeOpenBox(String name, {Duration timeout = const Duration(seconds: 8)}) async {